
all: compile_server compile_client

clean_all: clean_server clean_client

compile_server:
	cd server && $(MAKE)	

clean_server:
	cd server && $(MAKE) clean

compile_client:
	cd client && $(MAKE)	

clean_client:
	cd client && $(MAKE) clean


#client:
#	make -f client/makefile_client
