cc=gcc

all: task1 task2 task3 kill_proc

task1:
	$(CC) task1.c -o task1

task2:
	$(CC) task2.c -o task2

task3:
	$(CC) task3.c -o task3

kill_proc:
	$(CC) kill.c -o kill

clean:
	rm -f kill task1 task2 task3
